#!/bin/bash
#

makeRoute=$(pwd)

alias cdd="cd $makeRoute"
alias mk="cd $makeRoute && wait && make -j 8 && wait && cd -"
alias md="cd $makeRoute && wait && make debug -j 8 && wait && cd -"
alias mc="cd $makeRoute && wait && make clean && wait && cd -"
alias mcc="cd $makeRoute && wait && make cleaner && wait && cd -"
alias mm="mc && wait && mk"

alias R="cd $makeRoute/run && ./RunSimulation && wait && cd -"
alias C="cd $makeRoute"
